<a href="<?php echo $this->url(array('module'=>'protesto', 'controller' => 'notificador', 'action' => 'index'), null, true); ?>" id="back-link">voltar</a>
<h1>Lista de editais</h1>
<hr />
<div id="messenger"><?php echo $this->flashMessenger();?></div>

<table class="display" id="tabela" >
    <thead>
        <tr>
            <th> # </th>
            <th>Data</th>            
            <th>Edital</th>
        </tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->editais as $edital ) { $i=$i+1; ?>
            <tr>
            	<td><?php echo $i; ?></td>
                <td><?php echo $this->date($this->escape($edital->data_edital)); ?></td>
                
                 <td align="center">
                	<a href="<?php echo $this->url(array(
                					   'module'=>'protesto', 
                                       'controller' => 'verificador',
                                       'action'     => 'geraredital',
                                       'data'         => $this->escape($edital->data_edital))); ?>" title="Editar">ícone</a>
                    &nbsp;
                
                </td>
            </tr>
        <?php } ?>        
     </tbody>
          
</table>
