<a href="<?php echo $this->url(array('module'=>'protesto', 'controller' => 'notificador', 'action' => 'index'), null, true); ?>" id="back-link">voltar</a>

<h1>Lista de Títulos</h1>
<hr />
<div id="messenger"><?php echo $this->flashMessenger();?></div>

<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela" >
    <thead>
        <tr>
            <th> # </th>
            <th>Protocolo</th>
            <th>Nome</th>
            <th>CPF/CNPJ</th>            
            <th>Espécie</th>

        </tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->titulos as $titulo ) { $i=$i+1; ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $this->escape($titulo->protocolo); ?></td>
                <td>
                	<a href="<?php echo $this->url(array(
                					   'module'=>'protesto',
                                       'controller' => 'situacoes',
                                       'action'     => 'titulo',
                                       'idProtesto'         => $this->escape($titulo->idProtesto))); ?>" title="Ver Título"><?php echo $this->escape($titulo->nome); ?></a>
                </td> 
                <td><?php echo $this->documento($this->escape($titulo->numeroidentificacao), (int)$this->escape($titulo->tipoidentificacao)); ?></td>                
                <td><?php echo $this->escape($titulo->especie); ?></td>
            </tr>
        <?php } ?>        
     </tbody>
     
</table>
