<a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'cartorio', 'action'=> 'index'), null, true); ?>" id="back-link">voltar</a>

<h1>Autoridades</h1>

<ul>
	<li>
		<a href="<?php echo $this->url(array( 'module' => 'admin', 'controller' => 'cartorio', 'action' => 'cadastrarautoridade'), null, true); ?>" title="Cadastrar Autoridade">Cadastrar Autoridade</a>
	</li>
</ul>

<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela"  >
    <thead>
        <tr>
            <th> # </th>
            <th>Nome</th>
            <th>Cargo</th>            
            <th></th>
        </tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->autoridades as $autoridade ) { $i=$i+1; ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $this->escape($autoridade->nome); ?></td>
                <td><?php echo $this->escape($autoridade->cargo); ?></td>               
                <td align="center">
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin',
                                       'controller' => 'cartorio',
                                       'action'     => 'editarautoridade',
                                       'idAutoridade'         => $this->escape($autoridade->idAutoridade))); ?>" title="Editar">Editar</a>
                    &nbsp;
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin',
                                       'controller' => 'cartorio',
                                       'action'     => 'deletarautoridade',
                                       'idAutoridade'         => $this->escape($autoridade->idAutoridade))); ?>" title="Apagar">Apagar</a>
                </td>
            </tr>
        <?php } ?>        
     </tbody>
     
     
</table>
