<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'index'), null, true); ?>" id="back-link">voltar</a>

<h1>Feriados</h1>
<hr />
<div id="messenger"><?php echo $this->flashMessenger();?></div>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'cadastrarferiado'), null, true); ?>" title="Cadastrar Feriado">Cadastrar Feriado</a></li>
 </ul>
<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela"  >
    <thead>
        <tr>
            <th> # </th>
            <th>Data do Feriado</th>
			<th>Descricao</th>           
            <th></th>
        </tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->feriados as $feriado ) { $i=$i+1; ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo implode("/", array_reverse(explode("-", $this->escape($feriado->date)))); ?></td>
				<td><?php echo $this->escape($feriado->descricao); ?></td>               
                <td align="center">
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin',
                                       'controller' => 'cartorio',
                                       'action'     => 'editarferiado',
                                       'idFeriado'         => $this->escape($feriado->idFeriado))); ?>" title="Editar">Editar</a>
                    &nbsp;
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin',
                                       'controller' => 'cartorio',
                                       'action'     => 'deletarferiado',
                                       'idFeriado'         => $this->escape($feriado->idFeriado))); ?>" title="Apagar">Apagar</a>
                </td>
            </tr>
        <?php } ?>        
     </tbody>
     
</table>
