<div id="messenger"><?php echo $this->flashMessenger();?></div>
<ul id="menu-grid">
	<li>
		<a href="<?php echo $this->url(array('module'=>'protesto', 'controller' => 'index')); ?>" title="Protesto.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/seguranca.png" />
			<br/>
			Protesto
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'registro', 'action' => 'vigencias')); ?>" title="Administração dos dados sobre o Cartório e outros.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/administracao.png" />
			<br/>
			Administração Registro
		</a>
	</li>